language: objective-c

branches:
 only:
 - master

xcode_project: OTPGenerator/OTPGenerator.xcodeproj
xcode_scheme: OTPGeneratorTests
osx_image: xcode7
xcode_sdk: iphonesimulator9.0

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail && xcodebuild -project OTPGenerator/OTPGenerator.xcodeproj -scheme OTPGeneratorTests -sdk iphonesimulator test | xcpretty -c
